spring:
  datasource:
      # 自定义配置 - 默认数据库名称
      default-db: tenancy
      url: ${db-url:jdbc:mysql://localhost:3306/tenancy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&tinyInt1isBit=false&useSSL=false}
      username: ${db-username:root}
      password: ${db-password:root}
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis     
mybatis:
  configuration:
    # 开启打印日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
  # mapper.xml的位置
  mapper-locations: classpath*:mapper/**.xml
  # 实体位置
  type-aliases-package: com.dongx.accountbook.note.model

# mybatis分页插件
pagehelper:
  # 设置为true时，会将RowBounds第一个参数offset当成pageNum页码使用:
  offset-as-page-num: true
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  # 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
  page-size-zero: true
  # 页插件会从查询方法的参数值中，自动根据 params 配置的字段中取值，查找到合适的值时就会自动分页
  # params默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  support-methods-arguments: true

# 日志级别  
logging:
  level:
    # 开启mapper日志打印 
    com.dongx.accountbook.note: trace